name: ptcgb_flutter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.2 <3.0.0"
  flutter: ">1.22.4"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: any

  # For My Application
  draggable_scrollbar: any
  dio: any
  dio_http_cache: any
  json_annotation: any
  freezed_annotation: any
  shared_preferences: any
  enum_to_string: any
  google_fonts: any
  flutter_hooks: any
  hooks_riverpod: any
  state_notifier: any
  sqflite: any
  path: any
  charts_flutter: any
  equatable: any
  tuple: any
  path_provider: any
  rflutter_alert: any
  provider: any
  simple_logger: any
  auto_size_text: any
  pedantic_mono: any
  webview_flutter: ^1.0.7
  share: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen: any
  mockito: any
  build_runner: any
  freezed: any
  flutter_launcher_icons: any

flutter_icons:
  ios: true
  android: true
  image_path: 'assets/img/various/app_icon.png'
  adaptive_icon_background: 'assets/img/various/app_icon_background.png'


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    # debug
    - assets/img/test/

    # card
    - assets/img/cards/jp/sa/
    - assets/img/cards/jp/sm/605/
    - assets/text/cards/jp/sa/
    - assets/text/cards/jp/sm/

    # expansion
    - assets/text/expansions/
    - assets/img/expansions/sa/

    # generations
    - assets/img/generations/

    # other
    - assets/img/various/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

fonts:
  - family: NotoSansJP-Black
    font:
      - asset: assets/fonts/NotoSansJP-Black

use-material-design: true
